/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl.ui.contentassist

import fr.inria.diverse.hdl.ui.contentassist.AbstractHipsterDomainLanguageProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class HipsterDomainLanguageProposalProvider extends AbstractHipsterDomainLanguageProposalProvider {
}
