/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import fr.inria.diverse.hdl.hipsterDomainLanguage.Domain;
import fr.inria.diverse.hdl.hipsterDomainLanguage.Entity;
import fr.inria.diverse.hdl.hipsterDomainLanguage.Field;
import fr.inria.diverse.hdl.hipsterDomainLanguage.HipsterDomainLanguagePackage;
import fr.inria.diverse.hdl.hipsterDomainLanguage.Relation;
import fr.inria.diverse.hdl.services.HipsterDomainLanguageGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class HipsterDomainLanguageSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private HipsterDomainLanguageGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == HipsterDomainLanguagePackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case HipsterDomainLanguagePackage.DOMAIN:
				sequence_Domain(context, (Domain) semanticObject); 
				return; 
			case HipsterDomainLanguagePackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case HipsterDomainLanguagePackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case HipsterDomainLanguagePackage.RELATION:
				sequence_Relation(context, (Relation) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     elements+=DomainElement*
	 */
	protected void sequence_Domain(EObject context, Domain semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID fields+=Field*)
	 */
	protected void sequence_Entity(EObject context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID type=JHipsterType required?='required'?)
	 */
	protected void sequence_Field(EObject context, Field semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (type=RelationType from=[Entity|ID] fromRelation=ID to=[Entity|ID] toRelation=ID)
	 */
	protected void sequence_Relation(EObject context, Relation semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TYPE));
			if(transientValues.isValueTransient(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__FROM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__FROM));
			if(transientValues.isValueTransient(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__FROM_RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__FROM_RELATION));
			if(transientValues.isValueTransient(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TO) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TO));
			if(transientValues.isValueTransient(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TO_RELATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HipsterDomainLanguagePackage.Literals.RELATION__TO_RELATION));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getRelationAccess().getTypeRelationTypeEnumRuleCall_1_0(), semanticObject.getType());
		feeder.accept(grammarAccess.getRelationAccess().getFromEntityIDTerminalRuleCall_3_0_1(), semanticObject.getFrom());
		feeder.accept(grammarAccess.getRelationAccess().getFromRelationIDTerminalRuleCall_4_1_0(), semanticObject.getFromRelation());
		feeder.accept(grammarAccess.getRelationAccess().getToEntityIDTerminalRuleCall_6_0_1(), semanticObject.getTo());
		feeder.accept(grammarAccess.getRelationAccess().getToRelationIDTerminalRuleCall_7_1_0(), semanticObject.getToRelation());
		feeder.finish();
	}
}
