/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HipsterDomainLanguageUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return fr.inria.diverse.hdl.ui.internal.HipsterDomainLanguageActivator.getInstance().getInjector("fr.inria.diverse.hdl.HipsterDomainLanguage");
	}
	
}
