/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.inria.diverse.hdl.services.HipsterDomainLanguageGrammarAccess;

public class HipsterDomainLanguageParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HipsterDomainLanguageGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.inria.diverse.hdl.parser.antlr.internal.InternalHipsterDomainLanguageParser createParser(XtextTokenStream stream) {
		return new fr.inria.diverse.hdl.parser.antlr.internal.InternalHipsterDomainLanguageParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Domain";
	}
	
	public HipsterDomainLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HipsterDomainLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
