/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HipsterDomainLanguageRuntimeModule extends fr.inria.diverse.hdl.AbstractHipsterDomainLanguageRuntimeModule {

}
