/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import fr.inria.diverse.hdl.ui.internal.HipsterDomainLanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HipsterDomainLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return HipsterDomainLanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return HipsterDomainLanguageActivator.getInstance().getInjector(HipsterDomainLanguageActivator.FR_INRIA_DIVERSE_HDL_HIPSTERDOMAINLANGUAGE);
	}
	
}
