/*
 * generated by Xtext
 */
package fr.inria.diverse.hdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HipsterDomainLanguageUiModule extends fr.inria.diverse.hdl.ui.AbstractHipsterDomainLanguageUiModule {
	public HipsterDomainLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
